name: build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: kotokoto
          path: target/release/kotokoto.exe
